"use client";

import React from 'react';
import { X, FileText, Download, Printer, Shield, CheckCircle2 } from 'lucide-react';
import { DEMO_CASE_DATA } from '@/app/lib/mockData';

interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function ForensicReportModal({ isOpen, onClose }: ModalProps) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-[#111A2E] border border-[#1E2D4A] rounded-2xl w-full max-w-3xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Modal Header */}
        <div className="px-6 py-4 border-b border-[#1E2D4A] bg-[#0A0F1D] flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <FileText className="w-5 h-5 text-cyan-400" />
            <h3 className="text-base font-bold text-gray-100">FORENSIC GRAPH RESOLUTION REPORT</h3>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 text-gray-400 hover:text-white rounded-lg hover:bg-white/10"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Document Content Body */}
        <div className="p-8 overflow-y-auto font-sans space-y-6 text-sm text-gray-300">
          <div className="border-b border-gray-700 pb-4 text-center">
            <div className="text-xs font-mono text-cyan-400 font-bold uppercase">
              CONFIDENTIAL · FOR LAW ENFORCEMENT USE ONLY
            </div>
            <h2 className="text-xl font-black text-white mt-1">CYBER CRIME INVESTIGATION DOSSIER</h2>
            <div className="text-xs text-gray-400 font-mono mt-1">
              Case Reference: {DEMO_CASE_DATA.caseId} | Statutory Authority: {DEMO_CASE_DATA.statuteRef}
            </div>
          </div>

          {/* Section 1: Executive Summary */}
          <div className="space-y-2">
            <h4 className="text-xs font-mono text-amber-400 font-bold uppercase tracking-wider">
              1. EXECUTIVE SUMMARY
            </h4>
            <div className="bg-[#0A0F1D] p-4 rounded-lg border border-gray-800 space-y-2 text-xs">
              <div className="grid grid-cols-2 gap-2">
                <div><strong className="text-gray-400">Target Address:</strong> <span className="font-mono text-white">{DEMO_CASE_DATA.targetAddress}</span></div>
                <div><strong className="text-gray-400">Trace Value:</strong> <span className="font-mono text-amber-400">{DEMO_CASE_DATA.traceValue}</span></div>
                <div><strong className="text-gray-400">Attributed VASP:</strong> <span className="font-mono text-cyan-400">{DEMO_CASE_DATA.nearestVasp.name}</span></div>
                <div><strong className="text-gray-400">Attribution Confidence:</strong> <span className="font-mono text-cyan-400">{DEMO_CASE_DATA.nearestVasp.confidence}%</span></div>
              </div>
            </div>
          </div>

          {/* Section 2: Cryptographic Trail */}
          <div className="space-y-2">
            <h4 className="text-xs font-mono text-amber-400 font-bold uppercase tracking-wider">
              2. DETERMINISTIC TRANSACTION LINEAGE (6 HOPS)
            </h4>
            <div className="border border-gray-800 rounded-lg overflow-hidden text-xs">
              <table className="w-full text-left font-mono">
                <thead className="bg-[#0A0F1D] text-gray-400 border-b border-gray-800">
                  <tr>
                    <th className="p-2.5">From</th>
                    <th className="p-2.5">To</th>
                    <th className="p-2.5">Amount</th>
                    <th className="p-2.5">Latency</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-800/50">
                  {DEMO_CASE_DATA.edges.map((e, i) => (
                    <tr key={i} className="hover:bg-white/5">
                      <td className="p-2.5 text-cyan-400">{e.from}</td>
                      <td className="p-2.5 text-cyan-400">{e.to}</td>
                      <td className="p-2.5 text-amber-400">{e.amount}</td>
                      <td className="p-2.5 text-gray-400">{e.latency}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Section 3: Officer Sign-off */}
          <div className="pt-4 border-t border-gray-800 flex justify-between items-end text-xs font-mono">
            <div>
              <div className="text-gray-400">GENERATED BY:</div>
              <div className="text-white font-bold">{DEMO_CASE_DATA.investigatingOfficer}</div>
              <div className="text-cyan-400">IO ID: {DEMO_CASE_DATA.officerId}</div>
            </div>
            <div className="text-right">
              <div className="text-emerald-400 font-bold flex items-center justify-end">
                <CheckCircle2 className="w-4 h-4 mr-1" /> DIGITAL HASH SEALED
              </div>
              <div className="text-gray-500 text-[10px]">SHA-256: 8f92a104b2c89e71...</div>
            </div>
          </div>
        </div>

        {/* Modal Actions */}
        <div className="px-6 py-4 border-t border-[#1E2D4A] bg-[#0A0F1D] flex justify-end space-x-3">
          <button
            onClick={() => alert("Report downloaded as PDF dossier simulation.")}
            className="px-4 py-2 bg-[#1E2D4A] hover:bg-gray-700 text-gray-200 rounded-lg text-xs font-bold font-mono flex items-center space-x-2 transition-all"
          >
            <Download className="w-4 h-4" />
            <span>Download PDF</span>
          </button>
          <button
            onClick={onClose}
            className="px-5 py-2 bg-cyan-400 hover:bg-cyan-300 text-black rounded-lg text-xs font-bold font-mono transition-all shadow-[0_0_15px_rgba(0,229,255,0.3)]"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
